### ISSUE TITLE
Regarding the specific configuration of the anisotropic Gaussian kernel in the experiment

### ISSUE THREAD

**Issue by funnyWang-Echoes** [I2-Multimedia-Lab/DSAT#2]
Hello, thank you very much for your work. 
Can you tell me the specific parameters of the 9 anisotropic Gaussian kernels in the comparative experiments in the paper? In the article, I only saw the schematic diagram of the Gaussian kernel, but I don’t know how to implement it.

**Comment by nsqg** [comment]
Thank you for your attention to this work, I will give these parameters in the format of (lambda_1, lambda_2, theta), details are as follows: (2.0, 0.2, 0), (2.0, 1.0, 10), (3.5, 1.5, 30), (3.5, 2.0, 45), (3.5, 2.0, 90), (4.0, 1.5, 120), (4.0, 2.0, 135), (4.0, 3.0, 165), (4.0, 4.0, 180).

**Comment by funnyWang-Echoes** [comment]
Thanks a lot  for your reply.
