### ISSUE TITLE
question for the code

### ISSUE THREAD

**Issue by BONESWORD** [I2-Multimedia-Lab/DSAT#3]
你好！不好意思打扰了。我想请教一下代码的问题。在我尝试运行你们的代码的时候发现在model块中的 blindsr 文件中的main中有 model = BlindSR().cuda()这样一段代码，编译器提示有问题，似乎我并没有在代码中看到这个function BindSR()以此命名的方法，也没有在其他包中找到这样的function，请问如何解决这个问题呢？
<img width="345" alt="000916" src="https://github.com/I2-Multimedia-Lab/DSAT/assets/113486409/58b86b1f-87b5-4cdb-bb27-027169e007c6">

**Comment by BONESWORD** [comment]
Hi! Sorry for the interruption. I would like to ask a question about the code. When I try to run your code, I found that there is a code model = BlindSR().cuda() in the blindsr file main in the model block, and the compiler suggests that there is a problem, it seems that I don't see this function BindSR() named in this way in the code, and I don't find this kind of function in other packages, may I ask how to solve this problem? It seems that I don't see this function BindSR() named as such in the code, nor do I find such a function in other packages.

Translated with www.DeepL.com/Translator (free version)

**Comment by BONESWORD** [comment]
Hi! Sorry for the interruption. I would like to ask a question about the code. When I try to run your code, I found that there is a code model = BlindSR().cuda() in the blindsr file main in the model block, and the compiler suggests that there is a problem, it seems that I don't see this function BindSR() named in this way in the code, and I don't find this kind of function in other packages, may I ask how to solve this problem? It seems that I don't see this function BindSR() named as such in the code, nor do I find such a function in other packages.

**Comment by BONESWORD** [comment]
And whether the code is incomplete, e.g. whether it needs additional writing or tuning parameters

**Comment by nsqg** [comment]
这是我用来测试的代码，他没有任何用也不影响代码的运行，可以选择直接删除。
